start-at-login = true

after-startup-command = ['exec-and-forget sketchybar']
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

on-focus-changed = [
  'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_focus_change',
]

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 12
outer.bottom = 10
outer.top = 52
outer.right = 12

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.postmanlabs.mac'
run = 'move-node-to-workspace 1'


[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'Cisco-Systems.Spark'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'app.reflect.ReflectDesktop'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.docker.docker'
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = 'com.cisco.secureclient.gui'
run = 'move-node-to-workspace 5'


[mode.main.binding]

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

# Apps shortcuts
alt-t = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-b = 'exec-and-forget open -a /Applications/Brave Browser.app'
alt-n = 'exec-and-forget open -a /Applications/Reflect.app'
alt-c = 'exec-and-forget open -a /Applications/Claude.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

alt-shift-left = 'join-with left'
alt-shift-down = 'join-with down'
alt-shift-up = 'join-with up'
alt-shift-right = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
