#!/bin/bash

theme = light:rose-pine-dawn,dark:rose-pine

font-family = Code Saver
font-size = 15

cursor-invert-fg-bg = true
cursor-style = block
cursor-style-blink = false
mouse-hide-while-typing = true
shell-integration-features = no-cursor
macos-window-shadow = false
macos-icon = custom-style
macos-icon-frame = chrome

window-padding-y = 4,0
background-blur = true
background-opacity = 0.98

keybind = global:super+grave_accent=toggle_quick_terminal
quick-terminal-position = "center"
